name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-actions-cypress@v2
        with:
          build: npm run cypress:run
          start: npm start