name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.7
      uses: actions/setup-node@v1
      with:
        node-version: 14.7
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build